(() => {
 const tabs=[['tab-mindfulness','panel-mindfulness'],['tab-music','panel-music'],['tab-podcasts','panel-podcasts'],['tab-journaling','panel-journaling']];
 const primary=document.getElementById('primaryAction'),secondary=document.getElementById('secondaryAction'),label=document.getElementById('breathingLabel'),visual=document.getElementById('breathingVisual');
 let panel='panel-mindfulness',interval=null,remaining=0,phase=0,stageRemaining=0;
 const stages=[['Breathe in',4],['Hold',4],['Breathe out',6]];
 function announce(text){if(label)label.textContent=text;const live=document.getElementById('toolStatus');if(live)live.textContent=text;}
 function setPanel(id){panel=id;tabs.forEach(([b,p])=>{const active=p===id,button=document.getElementById(b),content=document.getElementById(p);button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));content.hidden=!active;});document.querySelectorAll('#durationChips .chip').forEach(b=>b.disabled=id!=='panel-mindfulness');primary.textContent=id==='panel-mindfulness'?'Start':id==='panel-journaling'?'Save Entry':'Play audio';secondary.textContent=id==='panel-mindfulness'?'Pause':id==='panel-journaling'?'Clear draft':'Pause audio';if(id!=='panel-mindfulness')pauseBreathing();renderTips(id);}
 tabs.forEach(([b,p])=>document.getElementById(b).addEventListener('click',()=>setPanel(p)));
 document.querySelectorAll('#durationChips .chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#durationChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');}));
 function startBreathing(){if(interval)return;if(remaining<=0){remaining=Number(document.querySelector('#durationChips .chip.active')?.dataset.minutes||1)*60;phase=0;stageRemaining=stages[0][1];}visual.classList.add('breathing-active');function show(){const current=stages[phase%3];label.textContent=current[0]+' · '+stageRemaining+'s in this step · '+remaining+'s total';visual.classList.remove('phase-inhale','phase-hold','phase-exhale');visual.classList.add('phase-'+['inhale','hold','exhale'][phase%3]);}show();interval=setInterval(()=>{remaining--;stageRemaining--;if(remaining<=0){stopBreathing();label.textContent='Session complete. Take a moment before continuing.';return;}if(stageRemaining<=0){phase=(phase+1)%3;stageRemaining=stages[phase][1];}show();},1000);}
 function stopBreathing(){if(interval){clearInterval(interval);interval=null;}visual.classList.remove('breathing-active','phase-inhale','phase-hold','phase-exhale');}
 function pauseBreathing(){if(interval){stopBreathing();announce('Paused · '+remaining+' seconds remaining');}}
 const journalInput=document.getElementById('journalInput'),journalList=document.getElementById('journalList'),journalStatus=document.getElementById('journalStatus'),storageKey='studentWellbeingJournal.v1';let entries=[];
 function loadEntries(){try{entries=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(entries))entries=[];}catch{entries=[];journalStatus.textContent='Browser storage is unavailable.';}}
 function renderEntries(){journalList.replaceChildren();if(!entries.length){const li=document.createElement('li');li.textContent='No saved entries yet.';li.className='meta';journalList.append(li);return;}entries.slice().reverse().forEach(entry=>{const li=document.createElement('li');li.className='journal-entry';const time=document.createElement('time');time.dateTime=new Date(entry.at).toISOString();time.textContent=new Date(entry.at).toLocaleString();const body=document.createElement('p');body.textContent=entry.text;const del=document.createElement('button');del.type='button';del.className='secondary-btn';del.textContent='Delete';del.setAttribute('aria-label','Delete entry from '+time.textContent);del.onclick=()=>{entries=entries.filter(x=>x.id!==entry.id);saveEntries('Entry deleted from this browser.');};li.append(time,body,del);journalList.append(li);});}
 function saveEntries(message){try{localStorage.setItem(storageKey,JSON.stringify(entries));journalStatus.textContent=message;renderEntries();}catch{journalStatus.textContent='Could not save. Browser storage may be full or unavailable.';}}
 function saveJournal(){const text=journalInput.value.trim();if(!text){journalStatus.textContent='Write a note before saving.';journalInput.focus();return;}entries.push({id:Date.now().toString(),at:Date.now(),text});saveEntries('Entry saved on this device.');journalInput.value='';}
 function clearDraft(){journalInput.value='';journalStatus.textContent='Draft cleared. Saved entries remain until you delete them.';journalInput.focus();}
 document.getElementById('saveJournalBtn').addEventListener('click',saveJournal);document.getElementById('clearJournalBtn').addEventListener('click',clearDraft);
 function playAudio(){const audios=[...document.getElementById(panel).querySelectorAll('audio')];if(!audios.length){announce('No audio is available in this section.');return;}const audio=audios.find(a=>a.paused)||audios[0];audio.play().then(()=>announce('Audio playing.')).catch(()=>announce('Audio could not start. Check the file and try again.'));audio.onended=()=>announce('Audio finished.');audio.onerror=()=>announce('Audio file could not be loaded.');}
 function pauseAudio(){const audios=[...document.getElementById(panel).querySelectorAll('audio')];audios.forEach(a=>a.pause());announce(audios.length?'Audio paused.':'No audio in this section.');}
 primary.addEventListener('click',()=>panel==='panel-mindfulness'?startBreathing():panel==='panel-journaling'?saveJournal():playAudio());
 secondary.addEventListener('click',()=>panel==='panel-mindfulness'?pauseBreathing():panel==='panel-journaling'?clearDraft():pauseAudio());
 const tips={mindfulness:['Mindfulness Tips','Breathe · ground · reset','Box breathing|Breathe in for 4, hold for 4, breathe out for 6.','Grounding|Name things you see, feel, hear, smell and taste.'],music:['Music Tips','Focus softly on sound','Choose one track|Listen at a comfortable volume.'],podcasts:['Listening Tips','Learn · reflect · apply','Pause when needed|Stop whenever you want.'],journaling:['Journaling Tips','Write · reflect · plan','Name it|Write down an emotion and its intensity.','One small step|Identify one manageable next step.']};
 function renderTips(id){const key=id.replace('panel-',''),data=tips[key],list=document.getElementById('tipsList');document.getElementById('tipsTitle').textContent=data[0];document.getElementById('tipsCount').textContent=data[1];list.replaceChildren();data.slice(2).forEach(x=>{const [h,d]=x.split('|'),li=document.createElement('li'),title=document.createElement('h3'),text=document.createElement('p');li.className='card';title.textContent=h;text.className='meta';text.textContent=d;li.append(title,text);list.append(li);});}
 loadEntries();renderEntries();setPanel(panel);
})();
