const SERVICES = [
 {id:'s1',name:'Individual counselling',types:['Counselling','One-on-one'],location:'Campus A',price:0,description:'Example listing. Verify service details with a provider.',access:'Example: booking may be required.',eligibility:'Verified.',url:'https://my.uq.edu.au/information-and-services/student-support/health-and-wellbeing/wellbeing-programs/emental-health-wellbeing-program'},
 {id:'s2',name:'Stress relief workshop (example)',types:['Workshop','Group'],location:'Campus A',price:20,description:'Example listing for a group stress management session.',access:'Check availability with a provider.',eligibility:'Not verified.',url:'https://my.uq.edu.au/information-and-services/student-support/health-and-wellbeing/mental-health-and-emotional-support/wellbeing-programs'},
 {id:'s3',name:'Phone support (example)',types:['Helpline','Phone'],location:'Online',price:0,description:'Example online support listing; not a verified emergency contact.',access:'Current contact details are not connected.',eligibility:'Verified.',url:'https://my.uq.edu.au/information-and-services/student-support/health-and-wellbeing/mental-health-and-emotional-support/counsellors'},
 {id:'s4',name:'Individual counselling (example)',types:['Counselling','One-on-one'],location:'Campus B',price:0,description:'Example listing for a counselling session.',access:'Contact provider to confirm access.',eligibility:'Not verified.',url:'https://my.uq.edu.au/information-and-services/student-support/health-and-wellbeing/mental-health-and-emotional-support/counsellors'},
 {id:'s5',name:'Mindfulness class (example)',types:['Class','Workshop'],location:'Campus A',price:15,description:'Example listing for a guided mindfulness class.',access:'Booking details are not connected.',eligibility:'Verified.',url:'https://my.uq.edu.au/information-and-services/student-support/health-and-wellbeing/wellbeing-programs/sharper-minds'}
];
const byId=id=>document.getElementById(id);
const locationSelect=byId('locationSelect'),typeChips=byId('typeChips'),minPrice=byId('minPrice'),maxPrice=byId('maxPrice');
const resultsList=byId('resultsList'),resultsCount=byId('resultsCount'),mapElement=byId('map');
let map=null,infoWindow=null;const markers=new Map();
function initFilters(){
 [...new Set(SERVICES.map(s=>s.location))].sort().forEach(loc=>{const o=document.createElement('option');o.value=loc;o.textContent=loc;locationSelect.append(o);});
 [...new Set(SERVICES.flatMap(s=>s.types))].sort().forEach(type=>{const b=document.createElement('button');b.type='button';b.className='chip';b.dataset.type=type;b.textContent=type;b.setAttribute('aria-pressed','false');b.onclick=()=>{const on=b.classList.toggle('active');b.setAttribute('aria-pressed',String(on));};typeChips.append(b);});
 document.querySelectorAll('.price-presets .chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.price-presets .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');const [a,z]=b.dataset.price.split('-').map(Number);minPrice.value=a;maxPrice.value=z;});
 byId('applyBtn').onclick=()=>{if(validatePrices())render();};byId('resetBtn').onclick=resetFilters;minPrice.oninput=maxPrice.oninput=()=>document.querySelectorAll('.price-presets .chip').forEach(x=>x.classList.remove('active'));
}
function validatePrices(){const a=minPrice.value===''?null:Number(minPrice.value),b=maxPrice.value===''?null:Number(maxPrice.value);if((a!==null&&a<0)||(b!==null&&b<0)||(a!==null&&b!==null&&a>b)){resultsCount.textContent='Check price range: minimum must be no greater than maximum.';return false;}return true;}
function resetFilters(){locationSelect.value='all';document.querySelectorAll('#typeChips .chip').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});document.querySelectorAll('.price-presets .chip').forEach(b=>b.classList.remove('active'));minPrice.value='';maxPrice.value='';render();}
function getFilters(){return{location:locationSelect.value,types:[...document.querySelectorAll('#typeChips .chip.active')].map(x=>x.dataset.type),min:minPrice.value===''?-Infinity:Number(minPrice.value),max:maxPrice.value===''?Infinity:Number(maxPrice.value)};}
function render(){const f=getFilters(),items=SERVICES.filter(s=>(f.location==='all'||s.location===f.location)&&(!f.types.length||f.types.every(t=>s.types.includes(t)))&&s.price>=f.min&&s.price<=f.max);resultsList.replaceChildren();resultsCount.textContent=items.length+' example '+(items.length===1?'service':'services')+' · illustrative prices';if(!items.length){const li=document.createElement('li');li.className='empty-state';li.textContent='No example services match. Change or reset the filters.';resultsList.append(li);}items.forEach(s=>resultsList.append(makeCard(s)));syncMarkers(items);}
function makeCard(s){const li=document.createElement('li');li.className='card service-card';li.dataset.id=s.id;
 const h=document.createElement('h3');h.textContent=s.name;const meta=document.createElement('div');meta.className='meta';meta.textContent=s.location+' · Example price: AUD $'+s.price;const desc=document.createElement('p');desc.textContent=s.description;
 const tags=document.createElement('div');tags.className='tags';s.types.forEach(t=>{const x=document.createElement('span');x.className='tag';x.textContent=t;tags.append(x);});
 const toggle=document.createElement('button');toggle.type='button';toggle.className='secondary-btn';toggle.textContent='Details & access';toggle.setAttribute('aria-expanded','false');
 const detail=document.createElement('div');detail.className='service-details';detail.hidden=true;
 [ 'How to access: '+s.access,'Eligibility: '+s.eligibility,'Prototype example only. Confirm service, price, eligibility and booking details with a provider.' ].forEach((text,i)=>{const p=document.createElement('p');p.textContent=text;if(i===2)p.className='demo-warning';detail.append(p);});
 const link=document.createElement(s.url?'a':'span');link.className='provider-link';link.textContent=s.url?'Open provider information':'Provider link not connected';if(s.url){link.href=s.url;link.target='_blank';link.rel='noopener noreferrer';}else link.setAttribute('aria-disabled','true');detail.append(link);
 toggle.onclick=()=>{detail.hidden=!detail.hidden;toggle.setAttribute('aria-expanded',String(!detail.hidden));toggle.textContent=detail.hidden?'Details & access':'Hide details';};
 li.append(h,meta,desc,tags,toggle,detail);li.onclick=e=>{if(!e.target.closest('button,a'))focusService(s.id);};return li;}
function syncMarkers(items){if(!map)return;const keep=new Set(items.map(s=>s.id));for(const [id,m]of markers)if(!keep.has(id)){m.setMap(null);markers.delete(id);}items.forEach(s=>{if(!markers.has(s.id)){const m=new google.maps.Marker({position:s.position,map,title:s.name});m.addListener('click',()=>selectCard(s.id));markers.set(s.id,m);}});}
function selectCard(id){document.querySelectorAll('.service-card').forEach(x=>x.classList.remove('active'));document.querySelector('.service-card[data-id="'+id+'"]')?.classList.add('active');}
function focusService(id){selectCard(id);const s=SERVICES.find(x=>x.id===id),m=markers.get(id);if(map&&m){map.panTo(s.position);map.setZoom(14);infoWindow.setContent(s.name+' · Example listing');infoWindow.open({map,anchor:m});}}
function showMapFallback(){mapElement.innerHTML='<div class="map-fallback"><strong>Map preview is optional</strong><p>Map API key not implemented due to privacy concern.</p></div>';}
function initMap(){if(!window.google?.maps){showMapFallback();return;}map=new google.maps.Map(mapElement,{center:{lat:-27.49,lng:153.015},zoom:12});infoWindow=new google.maps.InfoWindow();syncMarkers(SERVICES);}
function loadMap(){const key=window.APP_CONFIG?.googleMapsApiKey;if(!key){showMapFallback();return;}const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&callback=initMap';script.async=true;script.onerror=showMapFallback;document.head.append(script);}
window.initMap=initMap;document.addEventListener('DOMContentLoaded',()=>{initFilters();render();loadMap();});
